export type Locale = "en" | "fr";

export const translations = {
  // ===== NAVBAR =====
  nav: {
    features: { en: "Features", fr: "Fonctionnalités" },
    howItWorks: { en: "How it works", fr: "Comment ça marche" },
    pricing: { en: "Pricing", fr: "Tarifs" },
    login: { en: "Log in", fr: "Connexion" },
    ctaDesktop: { en: "Start for free", fr: "Commencer gratuitement" },
    ctaMobile: { en: "Try it", fr: "Essayer" },
  },

  // ===== HERO =====
  hero: {
    badge: { en: "New: Multi-format export and white label", fr: "Nouveau : Export multi-formats et white label" },
    title1: { en: "Customizable media kits", fr: "Des kits média" },
    titleHighlight: { en: "media kits", fr: "personnalisables" },
    title2: { en: " for your events", fr: " pour vos événements" },
    subtitle: {
      en: "Your speakers and exhibitors generate their own visuals while respecting your brand guidelines. No more back-and-forth with your designer.",
      fr: "Vos speakers et exposants génèrent leurs propres visuels en respectant votre charte graphique. Fini les allers-retours avec votre graphiste.",
    },
    cta: { en: "Create my first event", fr: "Créer mon premier événement" },
    ctaSecondary: { en: "See how it works", fr: "Voir comment ça marche" },
    mockupLabel: { en: "Template editor preview", fr: "Aperçu de l'éditeur de templates" },
  },

  // ===== SOCIAL PROOF =====
  social: {
    usedBy: { en: "Used by 500+ event organizers in Europe", fr: "Utilisé par 500+ organisateurs d'événements en France" },
    events: { en: "Events created", fr: "Événements créés" },
    visuals: { en: "Visuals generated", fr: "Visuels générés" },
    satisfaction: { en: "Client satisfaction", fr: "Satisfaction client" },
    genTime: { en: "Generation time", fr: "Temps de génération" },
  },

  // ===== VALUE PROP =====
  value: {
    badge: { en: "The lever your competitors aren't using yet", fr: "Le levier que vos concurrents n'utilisent pas encore" },
    title1: { en: "Turn every attendee into an ", fr: "Transformez chaque participant en " },
    titleHighlight: { en: "ambassador", fr: "ambassadeur" },
    title2: { en: " for your event", fr: " de votre événement" },
    subtitle: {
      en: "When your speakers, exhibitors and visitors share a personalized visual on their networks, your event gains visibility. For free. Organically.",
      fr: "Quand vos speakers, exposants et visiteurs partagent un visuel personnalisé sur leurs réseaux, c'est votre événement qui gagne en visibilité. Gratuitement. Organiquement.",
    },
    reach: { en: "Organic reach", fr: "Portée organique" },
    reachDesc: {
      en: "Every attendee who shares their visual exposes your brand to their entire network. 100 participants = thousands of impressions with zero ad spend.",
      fr: "Chaque participant qui partage son visuel expose votre marque à tout son réseau. 100 participants = des milliers d'impressions sans budget publicitaire.",
    },
    brand: { en: "Always on-brand", fr: "On-brand garanti" },
    brandDesc: {
      en: "No more DIY visuals on Canva with the wrong logo. Your templates lock the brand guidelines — only authorized fields are editable.",
      fr: "Fini les visuels faits maison sur Canva avec le mauvais logo. Vos templates verrouillent la charte graphique — seuls les champs autorisés sont modifiables.",
    },
    effort: { en: "Zero effort for you", fr: "Effort pour vous" },
    effortDesc: {
      en: "One link, that's it. Your attendees help themselves in 30 seconds. No email back-and-forth, no Photoshop files, no overwhelmed designer.",
      fr: "Un lien, c'est tout. Vos participants se servent eux-mêmes en 30 secondes. Plus d'allers-retours email, plus de fichiers Photoshop, plus de graphiste débordé.",
    },
    quote: {
      en: '"An event with 200 speakers who each share a visual means 200 posts talking about you. Without lifting a finger."',
      fr: '"Un événement avec 200 speakers qui partagent chacun un visuel, c\'est 200 publications qui parlent de vous. Sans lever le petit doigt."',
    },
    quoteNote: {
      en: "Content generated by your attendees is the best marketing there is.",
      fr: "Le contenu généré par vos participants est le meilleur marketing qui existe.",
    },
  },

  // ===== FEATURES =====
  features: {
    title1: { en: "Everything you need for ", fr: "Tout ce qu'il faut pour des kits média " },
    titleHighlight: { en: "professional", fr: "professionnels" },
    title2: { en: " media kits", fr: "" },
    subtitle: {
      en: "A complete platform to create, share and track your event media kits.",
      fr: "Une plateforme complète pour créer, partager et suivre vos kits média d'événements.",
    },
    editor: { en: "Template editor", fr: "Éditeur de templates" },
    editorDesc: {
      en: "Create visual templates with customizable zones. Your participants fill in, your brand is respected.",
      fr: "Créez des templates visuels avec zones personnalisables. Vos participants remplissent, votre charte est respectée.",
    },
    publicPage: { en: "Shareable public page", fr: "Page publique partageable" },
    publicPageDesc: {
      en: "One unique link per event. Your speakers and exhibitors access their media kit without creating an account.",
      fr: "Un lien unique par événement. Vos speakers et exposants accèdent à leur kit média sans créer de compte.",
    },
    preview: { en: "Real-time preview", fr: "Preview en temps réel" },
    previewDesc: {
      en: "Participants see their visual build live as they fill in their information.",
      fr: "Les participants voient leur visuel se construire en direct pendant qu'ils remplissent leurs informations.",
    },
    download: { en: "HD Download", fr: "Téléchargement HD" },
    downloadDesc: {
      en: "PNG export, formats optimized for social media. Professional quality guaranteed.",
      fr: "Export PNG, formats optimisés pour les réseaux sociaux. Qualité professionnelle garantie.",
    },
  },

  // ===== HOW IT WORKS =====
  howItWorks: {
    title: { en: "Up and running in 3 steps", fr: "Opérationnel en 3 étapes" },
    subtitle: {
      en: "From creation to sharing, everything is designed to be simple and fast.",
      fr: "De la création au partage, tout est pensé pour être simple et rapide.",
    },
    step1Title: { en: "Create your event", fr: "Créez votre événement" },
    step1Desc: {
      en: "Set up your event, upload your brand guidelines and define the customizable fields.",
      fr: "Configurez votre événement, uploadez votre charte graphique et définissez les champs personnalisables.",
    },
    step2Title: { en: "Design your templates", fr: "Designez vos templates" },
    step2Desc: {
      en: "Use the visual editor to create templates with variable zones: name, photo, title, company...",
      fr: "Utilisez l'éditeur visuel pour créer des templates avec des zones variables : nom, photo, titre, entreprise...",
    },
    step3Title: { en: "Share the link", fr: "Partagez le lien" },
    step3Desc: {
      en: "Send the unique link to your participants. They generate their personalized visuals in a few clicks.",
      fr: "Envoyez le lien unique à vos participants. Ils génèrent leurs visuels personnalisés en quelques clics.",
    },
  },

  // ===== PRICING =====
  pricing: {
    title1: { en: "Simple, ", fr: "Des tarifs " },
    titleHighlight: { en: "transparent", fr: "simples" },
    title2: { en: " pricing", fr: " et transparents" },
    subtitle: {
      en: "No commitment. Change plans at any time. Start for free.",
      fr: "Sans engagement. Changez de plan à tout moment. Commencez gratuitement.",
    },
    perMonth: { en: "/month", fr: "/mois" },
    popular: { en: "Popular", fr: "Populaire" },
    starterDesc: { en: "For small events and getting started.", fr: "Pour les petits événements et les premiers pas." },
    growthDesc: { en: "For organizers who are scaling up.", fr: "Pour les organisateurs qui passent à l'échelle." },
    proDesc: { en: "For agencies and large events.", fr: "Pour les agences et grands événements." },
    start: { en: "Get started", fr: "Commencer" },
    chooseGrowth: { en: "Choose Growth", fr: "Choisir Growth" },
    choosePro: { en: "Choose Pro", fr: "Choisir Pro" },
  },

  // ===== FINAL CTA =====
  cta: {
    title: { en: "Ready to transform your events?", fr: "Prêt à transformer vos événements ?" },
    subtitle: {
      en: "Join hundreds of organizers who use EventMediaKit to boost their event visibility.",
      fr: "Rejoignez les centaines d'organisateurs qui utilisent EventMediaKit pour booster la visibilité de leurs événements.",
    },
    button: { en: "Start for free", fr: "Commencer gratuitement" },
    note: { en: "No credit card required", fr: "Aucune carte bancaire requise" },
  },

  // ===== FOOTER =====
  footer: {
    tagline: {
      en: "The customizable media kit platform for event organizers.",
      fr: "La plateforme de kits média personnalisables pour les organisateurs d'événements.",
    },
    product: { en: "Product", fr: "Produit" },
    company: { en: "Company", fr: "Entreprise" },
    legal: { en: "Legal", fr: "Légal" },
    about: { en: "About", fr: "À propos" },
    contact: { en: "Contact", fr: "Contact" },
    legalNotice: { en: "Legal notice", fr: "Mentions légales" },
    terms: { en: "Terms of service", fr: "CGU" },
    privacy: { en: "Privacy policy", fr: "Confidentialité" },
    rights: { en: "All rights reserved.", fr: "Tous droits réservés." },
    rgpd: { en: "GDPR Compliant", fr: "Conforme RGPD" },
  },

  // ===== AUTH =====
  auth: {
    loginTitle: { en: "Log in", fr: "Connexion" },
    loginSubtitle: { en: "Access your organizer dashboard", fr: "Accédez à votre espace organisateur" },
    registerTitle: { en: "Create an account", fr: "Créer un compte" },
    registerSubtitle: { en: "Start creating your media kits in minutes", fr: "Commencez à créer vos kits média en quelques minutes" },
    email: { en: "Email", fr: "Email" },
    password: { en: "Password", fr: "Mot de passe" },
    orgName: { en: "Organization name", fr: "Nom de votre organisation" },
    orgPlaceholder: { en: "My Event 2026", fr: "Mon Salon 2026" },
    loginButton: { en: "Log in", fr: "Se connecter" },
    registerButton: { en: "Create my account", fr: "Créer mon compte" },
    noAccount: { en: "Don't have an account?", fr: "Pas encore de compte ?" },
    hasAccount: { en: "Already have an account?", fr: "Déjà un compte ?" },
    createAccount: { en: "Create an account", fr: "Créer un compte" },
    signIn: { en: "Log in", fr: "Se connecter" },
    or: { en: "or", fr: "ou" },
    minChars: { en: "At least 6 characters", fr: "Au moins 6 caractères" },
    brandingTitle1: { en: "Create customizable", fr: "Créez des kits média" },
    brandingTitle2: { en: "media kits", fr: "personnalisables" },
    brandingTitle3: { en: "for your events", fr: "pour" },
    brandingTitle4: { en: "", fr: "vos événements" },
    brandingSubtitle: {
      en: "Your attendees generate their own visuals while respecting your brand guidelines.",
      fr: "Vos participants génèrent leurs propres visuels en respectant votre charte graphique.",
    },
    brandingFooter: {
      en: "EventMediaKit — SaaS for event organizers",
      fr: "EventMediaKit — SaaS pour organisateurs d'événements",
    },
    loginError: { en: "Invalid email or password", fr: "Email ou mot de passe incorrect" },
    registerError: { en: "Error creating account", fr: "Erreur lors de la création du compte" },
    logging: { en: "Logging in...", fr: "Connexion..." },
    creating: { en: "Creating...", fr: "Création..." },
  },
} as const;

export type TranslationKey = keyof typeof translations;
